spring.application.name=spring-boot-testing
# server.error.include-message=never

spring.datasource.url=jdbc:postgresql://pg-1c7fc144-lineacr-4144.d.aivencloud.com:13188/defaultdb?ssl=require&user=avnadmin&password=AVNS_FcvPlDQ5zCIuvKUp7o3
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_FcvPlDQ5zCIuvKUp7o3

 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

#valkey redis configuration 

spring.data.redis.client-type=lettuce
spring.data.redis.host=valkey-server-lineacr-4144.c.aivencloud.com
spring.data.redis.port=13189
spring.data.redis.username=default
spring.data.redis.password=AVNS_w-IWO34pqQVDLAQ0rRo
spring.data.redis.ssl.enabled=false

# actuator properties
# management.endpoints.web.base-path=

# management.endpoints.web.exposure.include=*
# management.endpoint.health.show-details=always
# management.endpoint.heapdump.access=unrestricted

